export const users = [
  {
    id: 1,
    name: "Luciana Julia",
    location: "Portland illinois",
    distance: 11,
    fetish: "foot fetish",
    age: 23,
    bio: "Love to smell feet",
    image: require("../assets/user1.jpg"),
  },
  {
    id: 2,
    name: "William Ida",
    location: "Portland illinois",
    distance: 11,
    fetish: "ear fetish",
    age: 24,
    bio: "I like to lick your ears",
    image: require("../assets/user2.jpg"),
  },
  {
    id: 3,
    name: "Tracy Fradera",
    location: "Portland illinois",
    distance: 11,
    fetish: "hair fetish",
    age: 24,
    bio: "Love to smell hair",
    image: require("../assets/user3.jpg"),
  },
  {
    id: 4,
    name: "Doreatha Grave",
    location: "Portland illinois",
    distance: 11,
    fetish: "hair fetish",
    age: 24,
    bio: "Love to feel washed hair",
    image: require("../assets/user4.jpg"),
  },
  {
    id: 5,
    name: "Jacquetta Bobalik",
    location: "Portland illinois",
    distance: 11,
    fetish: "foot fetish",
    age: 24,
    bio: "Love to smell feet",
    image: require("../assets/user5.jpg"),
  },
  {
    id: 6,
    name: "Velia Kwasniak",
    location: "Portland illinois",
    distance: 11,
    fetish: "foot fetish",
    age: 24,
    bio: "Love to smell feet",
    image: require("../assets/user6.jpg"),
  },
  {
    id: 7,
    name: "Karisa Delorm",
    location: "Portland illinois",
    distance: 11,
    fetish: "foot fetish",
    age: 24,
    bio: "Love to smell feet",
    image: require("../assets/user7.jpg"),
  },
  {
    id: 8,
    name: "Cecil Agudelo",
    location: "Portland illinois",
    distance: 11,
    fetish: "foot fetish",
    age: 24,
    bio: "Love to smell feet",
    image: require("../assets/user8.jpg"),
  },
];

export const profile = [
  {
    id: 1,
    name: "Kobe Van Dyck",
    location: "Mechelen",
    distance: 11,
    fetish: "Melolagnia",
    age: 19,
    bio: "I make sick beats that I really love and have sexual fantasies about.",
    image: require("../assets/kobe.jpg"),
  },
];
